### PR TITLE
export XHRFactory with method to create new instance of default XHRApi

### PR DESCRIPTION
**Pull request by liyinsg**

### CODE REVIEW

**Comment by gautamsi** [comment]
can you not do this by setting new XHR instance to `ExchangeService. XHRApi = new xhrdefault() || new XHRNTLM() || XHRCookies() || new xhrCustom()`? (indicative api names)

if I accept your PR, it will break. https://github.com/gautamsi/ews-javascript-api/blob/1ffc1edde982fd5bd061cdcdb0a720fd8c64be97/src/js/ConfigurationApi.ts#L8

**Comment by liyinsg** [comment]
I removed first commit, keep second commit to get the default XHR api.
In this case, ConfigurationApi should not be used when multiple ExchangeService instances are created.

**Comment by gautamsi** [comment]
I would suggest converting `static get XHRDefaultApi()` to `static newXHRApi()`  (as static method). the name `XHRDefaultApi` does not sound like new instance every time.

**Comment by liyinsg** [comment]
Changed as suggested, thanks

**Pull request merged**
